-- V3: 운영 DB 에 누락된 파이프라인 테이블 3종을 생성한다.
--
-- 배경:
--   운영(Railway) 은 ddl-auto: validate 로 부팅하는데, 아래 3개 테이블이 존재하지 않아
--   entityManagerFactory 생성이 실패했다 (Schema-validation: missing table [coverage_bucket] 외).
--   해당 테이블들은 로컬에서 ddl-auto: update 로만 만들어져 있었고, Flyway 로 명시된 적이 없다.
--
-- 대상 테이블:
--   - coverage_bucket                       (CoverageBucket)
--   - patch_version                         (PatchVersion)
--   - daily_pipeline_state                  (DailyPipelineState)
--   - daily_pipeline_seed_completed_tiers   (DailyPipelineState.seedCompletedTiers @ElementCollection 자식 테이블)
--
-- 대상 환경:
--   - 운영(Railway): 이 스크립트가 실행되어 4개 테이블을 새로 생성한다.
--   - 새 환경(fresh DB): CREATE TABLE IF NOT EXISTS 덕분에 안전하게 건너뛰거나 생성한다.
--   - 테스트(H2): spring.flyway.enabled=false 이므로 실행되지 않는다.
--
-- 컬럼 타입은 Hibernate 6.x PostgreSQL Dialect 기본 매핑을 따른다.
--   String               -> varchar(255)
--   Long @Id IDENTITY    -> bigint generated by default as identity
--   int                  -> integer
--   OffsetDateTime       -> timestamp(6) with time zone
--   LocalDate            -> date
--   @Enumerated(STRING)  -> varchar(255)

CREATE TABLE IF NOT EXISTS coverage_bucket (
    id                      bigint                       GENERATED BY DEFAULT AS IDENTITY,
    patch                   varchar(255)                 NOT NULL,
    tier                    varchar(255)                 NOT NULL,
    current_page            integer                      NOT NULL,
    current_division        varchar(3)                   NOT NULL,
    daily_seed_reset_at     timestamp(6) with time zone,
    daily_pages_processed   integer                      NOT NULL,
    division_cycle_count    integer                      NOT NULL,
    created_at              timestamp(6) with time zone  NOT NULL,
    updated_at              timestamp(6) with time zone  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_coverage_bucket_patch_tier UNIQUE (patch, tier)
);

CREATE TABLE IF NOT EXISTS patch_version (
    id           bigint                       GENERATED BY DEFAULT AS IDENTITY,
    patch        varchar(255)                 NOT NULL,
    released_at  timestamp(6) with time zone  NOT NULL,
    created_at   timestamp(6) with time zone  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_patch_version_patch UNIQUE (patch)
);

CREATE TABLE IF NOT EXISTS daily_pipeline_state (
    id                       bigint                       GENERATED BY DEFAULT AS IDENTITY,
    pipeline_date            date                         NOT NULL,
    seed_api_calls_used      integer                      NOT NULL,
    collect_api_calls_used   integer                      NOT NULL,
    created_at               timestamp(6) with time zone  NOT NULL,
    updated_at               timestamp(6) with time zone  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_daily_pipeline_state_date UNIQUE (pipeline_date)
);

CREATE TABLE IF NOT EXISTS daily_pipeline_seed_completed_tiers (
    daily_pipeline_state_id  bigint        NOT NULL,
    tier                     varchar(255)  NOT NULL,
    CONSTRAINT fk_daily_pipeline_seed_completed_tiers_state
        FOREIGN KEY (daily_pipeline_state_id) REFERENCES daily_pipeline_state (id)
);
